// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20231201011058_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Turkey Ship-Co",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Japan Ship-Co",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monaco Ship-Co",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Spain Ship-Co",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Germany Ship-Co",
                            OwnerId = 3
                        });
                });

            modelBuilder.Entity("Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("150dffda-3026-4502-b310-8b19c7893f82"),
                            CompanyId = 1,
                            Name = "Hakkı Usta",
                            Salary = 15000.0
                        },
                        new
                        {
                            Id = new Guid("5af64fe6-5094-48d4-a422-ea261d72736c"),
                            CompanyId = 1,
                            Name = "Suat Usta",
                            Salary = 20000.0
                        },
                        new
                        {
                            Id = new Guid("f534024d-5f26-4786-9249-da3e8af14272"),
                            CompanyId = 1,
                            Name = "Ahmet Usta",
                            Salary = 5000.0
                        },
                        new
                        {
                            Id = new Guid("7b67c7c5-001e-4ef1-9697-03c9448876c2"),
                            CompanyId = 2,
                            Name = "Hitachi Usta",
                            Salary = 25000.0
                        },
                        new
                        {
                            Id = new Guid("97cdb7cf-363f-447b-8e51-9dc3d0a8a1eb"),
                            CompanyId = 2,
                            Name = "Makita Usta",
                            Salary = 30000.0
                        },
                        new
                        {
                            Id = new Guid("3ecb3928-6d42-4a6a-bf85-af2b9ac6ea70"),
                            CompanyId = 2,
                            Name = "Ryobi Usta",
                            Salary = 45000.0
                        },
                        new
                        {
                            Id = new Guid("d446fdb6-560f-4f54-ac6e-0fce609ea568"),
                            CompanyId = 3,
                            Name = "Buffon Usta",
                            Salary = 20000.0
                        },
                        new
                        {
                            Id = new Guid("41793fae-baa1-479e-b1a3-7809440af4d4"),
                            CompanyId = 3,
                            Name = "Hans Usta",
                            Salary = 22000.0
                        },
                        new
                        {
                            Id = new Guid("70f6a785-073c-403e-81ae-0dd788892085"),
                            CompanyId = 3,
                            Name = "Tsubasa Usta",
                            Salary = 23232.0
                        },
                        new
                        {
                            Id = new Guid("7c388946-875f-4a0b-9546-2451c914ac2a"),
                            CompanyId = 3,
                            Name = "Nail Usta",
                            Salary = 33000.0
                        },
                        new
                        {
                            Id = new Guid("4202e56e-ed55-4a58-b05f-b15f9adc5560"),
                            CompanyId = 4,
                            Name = "Iglesias Usta",
                            Salary = 60000.0
                        });
                });

            modelBuilder.Entity("Models.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tuna GÜL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zatoichi Kiroshi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Raquel Sanchez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emilio Zanetti"
                        });
                });

            modelBuilder.Entity("Models.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorCompanyId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipColor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorCompanyId");

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorCompanyId = 1,
                            Length = 50.0,
                            Name = "Uçak Gemisi",
                            ShipColor = 5
                        },
                        new
                        {
                            Id = 2,
                            AuthorCompanyId = 1,
                            Length = 30.0,
                            Name = "Yük Gemisi",
                            ShipColor = 4
                        },
                        new
                        {
                            Id = 3,
                            AuthorCompanyId = 1,
                            Length = 30.0,
                            Name = "Buğday Gemisi",
                            ShipColor = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorCompanyId = 2,
                            Length = 40.0,
                            Name = "Oil Ship",
                            ShipColor = 0
                        },
                        new
                        {
                            Id = 5,
                            AuthorCompanyId = 2,
                            Length = 30.0,
                            Name = "Car Ship",
                            ShipColor = 1
                        },
                        new
                        {
                            Id = 6,
                            AuthorCompanyId = 2,
                            Length = 25.0,
                            Name = "Drone Ship",
                            ShipColor = 1
                        },
                        new
                        {
                            Id = 7,
                            AuthorCompanyId = 3,
                            Length = 10.0,
                            Name = "Fisher Boat",
                            ShipColor = 0
                        },
                        new
                        {
                            Id = 8,
                            AuthorCompanyId = 3,
                            Length = 5.0,
                            Name = "Mussell Hunter",
                            ShipColor = 5
                        });
                });

            modelBuilder.Entity("Models.Entities.Company", b =>
                {
                    b.HasOne("Models.Entities.Owner", "Owner")
                        .WithMany("Companies")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Models.Entities.Employee", b =>
                {
                    b.HasOne("Models.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Entities.Ship", b =>
                {
                    b.HasOne("Models.Entities.Company", "AuthorCompany")
                        .WithMany()
                        .HasForeignKey("AuthorCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorCompany");
                });

            modelBuilder.Entity("Models.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Models.Entities.Owner", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
